services:
  cloudpybara:
    image: ghcr.io/jameslufz/cloudpybara:latest
    container_name: cloudpybara
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - lufz-network

networks:
  lufz-network:
    external: true